### ISSUE TITLE
Error: WebKitCSSMatrix is not defined

### ISSUE THREAD

**Issue by drale2k** [beastaugh/firmin#22]
Hey, i`m using Firmin for  the first time and i always get this Error "WebKitCSSMatrix is not defined" in the Firebug Console.

This error does not show up in WebKit browsers but it does not work anyway. Any idea what could cause this?

**Comment by drale2k** [comment]
In Webkit Browsers i get this error after trying to use any function

"TypeError: 'null' is not an object (evaluating 'element.style')" on Line 828

**Comment by beastaugh** [comment]
Version 1.0 [doesn't support](http://extralogical.net/projects/firmin/#supported-platforms) any browsers other than those running relatively recent versions of WebKit. Version 1.1, once I have the opportunity to fix a few outstanding bugs, will add some limited support (no 3d) for Firefox and Opera. More work is needed to do this because neither of those browsers fully implements the CSS transform specification, which [requires](http://www.w3.org/TR/css3-3d-transforms/#cssmatrix-interface) the provision of a user-accessible implementation of the `CSSMatrix` interface. Version 1.1 includes `FirminCSSMatrix`, a JavaScript implementation of that interface, but there are still a few kinks I need to iron out before it's ready to release.

Could you post a test case where the second error you mention occurs, so I can see what might be going on?

**Comment by drale2k** [comment]
Here is an example http://pastebin.com/zz517q1n

The same error occured when i downloaded your demo and tried the animate.html

ps: In all demo html files it links to lib/all-min.js, but there is not 'lib' folder at all, so i changed the src to '../src/firmin.js'

Any idea when you will be able to release 1.1?

**Comment by beastaugh** [comment]
As explained in the project's `README` file, you need to build the library in order to run the tests. This requires a few prerequisites, all of which are listed there.

Your example code isn't working because the script is executing before the element you're trying to animate is registered in the DOM. Try moving the test script to the bottom of the page.

I'm afraid I don't have an ETA for 1.1; it basically depends on my having sufficient spare time. Hopefully it will be reasonably soon.
